apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capi-provider-role
  namespace: ce-apac
  annotations:
    #argocd.argoproj.io/sync-wave: "451"
    #helm.sh/hook-weight: "451"
rules:
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agents
  verbs:
  - '*'