apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: 'ce-apac'
  namespace: 'ce-apac'
  annotations:
    cluster.open-cluster-management.io/hypershiftdeployment: local-cluster/ce-apac 
    cluster.open-cluster-management.io/managedcluster-name: ce-apac
    argocd.argoproj.io/sync-wave: "470"
    helm.sh/hook-weight: "470"
  labels:
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.11.27-multi
  pullSecret:
    name: pullsecret-cluster-ce-apac
  sshKey:
    name: sshkey-cluster-ce-apac
  networking:
    podCIDR: 10.132.0.0/14
    serviceCIDR: 172.31.0.0/16
    machineCIDR: 10.39.127.0/24 
    networkType: OVNKubernetes
  platform:
    type: Agent
    agent:
      agentNamespace: 'ce-apac'
  infraID: 'ce-apac'
  dns:
    baseDomain: 'na.cloud.techzone.ibm.com'
  services:
  - service: APIServer
    servicePublishingStrategy:
      nodePort:
          address: api.ce-apac.na.cloud.techzone.ibm.com
          port: 31084
      type: NodePort
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route