apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: 'ce-apac-sno'
  namespace: 'ce-apac-sno'
  labels:
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.12.2-multi
  pullSecret:
    name: pullsecret-cluster-ce-apac-sno
  sshKey:
    name: sshkey-cluster-ce-apac-sno
  networking:
    podCIDR: 10.132.0.0/14
    serviceCIDR: 172.31.0.0/16
    machineCIDR: 
    networkType: 
  platform:
    type: Agent
    agent:
      agentNamespace: 'itzdev-na'
  infraID: 'ce-apac-sno'
  dns:
    baseDomain: 'na.cloud.techzone.ibm.com'
  services:
  - service: APIServer
    servicePublishingStrategy:
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route