apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: ce-apac
  namespace: ce-apac
  annotations:
    cluster.open-cluster-management.io/hypershiftdeployment: ce-apac/ce-apac
    cluster.open-cluster-management.io/managedcluster-name: ce-apac
  #  argocd.argoproj.io/sync-wave: "460"
  #  helm.sh/hook-weight: "460"
spec:
  fips: false
  release:
    image: 'quay.io/openshift-release-dev/ocp-release:4.11.27-multi'
  controllerAvailabilityPolicy: SingleReplica
  pullSecret:
    name: openshift-pull-secret
  sshKey:
    name: sshkey-cluster
  issuerURL: 'https://kubernetes.default.svc'
  autoscaling: {}
  olmCatalogPlacement: management
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    serviceNetwork:
      - cidr: 172.31.0.0/16
    machineNetwork:
      - cidr: 10.39.127.0/24 
    networkType: OVNKubernetes
  platform:
    type: Agent
    agent:
      agentNamespace: ce-apac
  infraID: ce-apac
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 4Gi
        type: PersistentVolume
    managementType: Managed
  infrastructureAvailabilityPolicy: SingleReplica
  dns:
    baseDomain: 'na.cloud.techzone.ibm.com'
  services:
  - service: APIServer
    servicePublishingStrategy:
      nodePort:
          address: api.ce-apac.na.cloud.techzone.ibm.com
          port: 31084
      type: NodePort
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route