apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: 'nodepool-ce-apac-1'
  namespace: 'ce-apac'
spec:
  clusterName: 'ce-apac'
  replicas: 1
  management:
    autoRepair: false
    upgradeType: InPlace
  platform:
    type: Agent
    agent:
      agentLabelSelector:
        matchLabels: 
          agentclusterinstalls.extensions.hive.openshift.io/location: North-America
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.12.2-multi