---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: ce-apac
  namespace: ce-apac
  labels:
    name: ce-apac
    cloud: vSphere
    vendor: OpenShift
    datacenter: IBMCloud
    cluster: itzdev-wdc07
    cluster-name: ce-apac
  annotations:
    argocd.argoproj.io/sync-wave: "485"
    helm.sh/hook-weight: "485"
spec:
  clusterName: ce-apac
  clusterNamespace: ce-apac
  clusterLabels:
    name: ce-apac
    cloud: BareMetal
    vendor: OpenShift
    datacenter: IBMCloud
    cluster: itzdev-wdc07
    cluster-name: ce-apac
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
