---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: ce-apac
  annotations:
    cluster.open-cluster-management.io/hypershiftdeployment: local-cluster/ce-apac
    import.open-cluster-management.io/hosting-cluster-name: local-cluster 
    import.open-cluster-management.io/klusterlet-deploy-mode: Hosted
    open-cluster-management/created-via: other
    #argocd.argoproj.io/sync-wave: "480"
    #helm.sh/hook-weight: "480"
  labels:
    name: ce-apac
    cloud: auto-detect
    vendor: OpenShift
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
