---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: ce-apac
  annotations:
    cluster.open-cluster-management.io/hypershiftdeployment: ce-apac/ce-apac-ce-apac
    cluster.open-cluster-management.io/provisioner: ce-apac-ce-apac.ce-apac.HypershiftDeployment.cluster.open-cluster-management.io
    import.open-cluster-management.io/hosting-cluster-name: local-cluster 
    import.open-cluster-management.io/klusterlet-deploy-mode: Hosted
    open-cluster-management/created-via: other
    argocd.argoproj.io/sync-wave: "480"
    helm.sh/hook-weight: "480"
  labels:
    name: ce-apac
    cloud: Other
    vendor: OpenShift
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
