---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: ce-apac-cluster-config
  namespace: itzdev-na
  labels:
    name: ce-apac
    cloud: vSphere
    vendor: OpenShift
    datacenter: IBMCloud
    cluster: itzdev-wdc07
    cluster-name: ce-apac
data:
  cluster_name: ce-apac
  cluster_provider: vsphere
  cluster_type: vSphere

  node_boot_timeout: '30'
  node_count: '1'

  vsphere_datacenter: IBMCloud 
  vsphere_cluster: itzdev-wdc07
  vsphere_datastore: datastore-wdc07-vm02
  vsphere_iso_folder: ISO
  vsphere_vm_folder: rhacm-hub-spoke

  vsphere_network: itzdev-wdc07-private

  cluster_nodes: '[{ "name": "ce-apac", "type": "sno-node", "vm": { "cpu_cores": 8, "cpu_sockets": 1, "cpu_threads": 1, "memory": 16384, "disks": [{ "size": 120, "name": "boot" }]}, "network": { "interfaces": [{ "name": "ens192", "mac_address": "00:50:56:a7:32:d3", "dhcp": true }]}}]'