---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: ce-apac-vsphere-bootstrap
  namespace: ce-apac
  labels:
    name: ce-apac
    cloud: vSphere
    vendor: OpenShift
    datacenter: IBMCloud
    cluster: itzdev-wdc07
    cluster-name: ce-apac
  annotations:
    #argocd.argoproj.io/sync-wave: "465"
    #helm.sh/hook-weight: "465"
spec:
  tower_auth_secret: ansible
  job_template_name: Create HostedCluster vSphere Infrastructure
  extra_vars:
    vcenter_credentials_secret_namespace: ce-apac
    vcenter_credentials_secret_name: vcenter-credentials

    infraenv_namespace: ce-apac
    infraenv_name: itzdev-na

    cluster_configmap_namespace: ce-apac
    cluster_configmap_name: ce-apac-cluster-config
  #runner_image: "quay.io/benswinneyau/aap-rr"
  #runner_version: "latest"