---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-pull-secret 
  namespace: ce-apac 
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "otp-credentials/otp-deployment-pull-secret"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: '.*'
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
  labels:
    name: ce-apac
    cloud: vSphere
    vendor: OpenShift
    datacenter: IBMCloud
    cluster: itzdev-wdc07
    cluster-name: ce-apac