---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  annotations:
    agentBareMetal-agentSelector/autoSelect: "true"
  name: pointcook
  namespace: pointcook
  labels:
    name: pointcook
    cloud: vSphere
    vendor: OpenShift
    datacenter: Datacenter
    cluster: Cluster
    cluster-name: pointcook
    #hive.openshift.io/cluster-platform: agent-baremetal
    #cluster.open-cluster-management.io/clusterset: default
spec:
  baseDomain: home.swinney.io
  clusterName: pointcook
  #controlPlaneConfig:
  #  servingCertificates: {}
  installed: false
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: pointcook
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: pointcook
  pullSecretRef:
    name: openshift-pull-secret
