---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: pointcook-cluster-config
  namespace: pointcook
  labels:
    name: pointcook
    cloud: vSphere
    vendor: OpenShift
    datacenter: Datacenter
    cluster: Cluster
    cluster-name: pointcook
data:
  cluster_name: pointcook
  cluster_provider: vsphere
  cluster_type: vSphere

  node_boot_timeout: '30'
  node_count: '1'

  vsphere_datacenter: Datacenter 
  vsphere_cluster: Cluster 
  vsphere_datastore: vm-storage
  vsphere_network: VM Network

  cluster_nodes: '[{ "name": "pointcook", "type": "sno-node", "vm": { "cpu_cores": 8, "cpu_sockets": 1, "cpu_threads": 1, "memory": 16384, "disks": [{ "size": 120, "name": "boot" }]}, "network": { "interfaces": [{ "name": "ens192", "mac_address": "00:50:56:68:47:10", "dhcp": true }]}}]'